### ISSUE TITLE
Does not scroll

### ISSUE THREAD

**Issue by DevTard** [davecom/DKDropMenu#10]
When the number of items is large and the menu goes past the bottom of the screen, it is not possible to select the items that are past the bottom. I would have thought that it would scroll? This is the first time i have used this so i do not know if this worked previously. 

Even with this issue, it is still awesome!

**Comment by davecom** [comment]
Hi @FLM96,
That is accurate - there is no scrolling. You may be able to get around that by placing it within a UIScrollView.
Hope this helps!
