### ISSUE TITLE
How to Implement Collapsed?

### ISSUE THREAD

**Issue by Saravana181187** [davecom/DKDropMenu#12]
How to get last selected Item from dropmenu, what is the purpose of func collapsedChanged() and how to use this, Mainly I want to get last selected data?

**Comment by davecom** [comment]
Hi @Saravana181187 ,
To get the last selected item you need to implement `DKDropMenuDelegate` in some class and then set an instance of it as the delegate. e.g. `dropMenu.delegate = yourInstance`. The `itemSelected()` method will then be called every time an item is selected including the index and name of the item selected.
Hope this helps!

**Comment by Saravana181187** [comment]
Sorry I can't Understand, Can you give some sample code please?

**Comment by davecom** [comment]
Download the sample project in the repository. Specifically look at [`ViewController`](https://github.com/davecom/DKDropMenu/blob/master/DKDropMenu/ViewController.swift).
