### ISSUE TITLE
Doesn't compile when pulled in through CocoaPods

### ISSUE THREAD

**Issue by nlabhart** [davecom/DKDropMenu#3]
Pulled in the drop menu via CocoaPods. When I tried to build, I get three errors. 
![screen shot 2015-09-20 at 1 57 45 pm](https://cloud.githubusercontent.com/assets/3129166/9982371/98e3ac1e-5f9f-11e5-94a0-9bb8d86fe6fb.png)

**Comment by nlabhart** [comment]
I'm assuming this has to do with Swift 2.0 support.

**Comment by davecom** [comment]
Yes, the current version is built for Swift 2.  Use release 0.1.4 for Swift 1.2 support.

**Comment by nlabhart** [comment]
Got it! Thank you.
