### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by allakin** [davecom/DKDropMenu#8]
addNewTackViewController(UIViewController) does not conform to protocol DKDropMenuDelegate
https://monosnap.com/file/cqMkptSWbe2VbFQ5jwOltXlwEQYzCA
https://monosnap.com/file/Ybree3r8KHnRs7e360mcshLNMjHGWa
Help me plz!  :)

**Comment by davecom** [comment]
@allakin 
`addNewTackViewController` needs to conform to the `DKDropMenuDelegate` which means implementing the `itemSelected()` method.

**Comment by allakin** [comment]
@davecom 
Thank you!
